### ISSUE TITLE
Yabs crashes at start up

### ISSUE THREAD

**Issue by susnux** [anti43/openyabs#13]
When trying to run yabs it crashes, using version 1.2beta6:

 /tmp/Yabs-1.2-beta6-package/yabs.sh 
Starting YABS..
Java exec found in PATH. Verifying..
Java version found:  [java = 1.7.0_51]
Java version ok..
Program directory: /tmp/Yabs-1.2-beta6-package
Loading YABS
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli2/Option
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
        at java.lang.Class.getMethod0(Class.java:2774)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli2.Option
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more
YABS TERMINATED.

**Comment by anti43** [comment]
lib directory missing locally!
